//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.ISrv")]
    public interface ISrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrv/AddRule", ReplyAction="http://tempuri.org/ISrv/AddRuleResponse")]
        void AddRule(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrv/DelRule", ReplyAction="http://tempuri.org/ISrv/DelRuleResponse")]
        void DelRule(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvChannel : Server.ISrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvClient : System.ServiceModel.ClientBase<Server.ISrv>, Server.ISrv {
        
        public SrvClient() {
        }
        
        public SrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddRule(string data) {
            base.Channel.AddRule(data);
        }
        
        public void DelRule(string data) {
            base.Channel.DelRule(data);
        }
    }
}
