//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CAService.ICA")]
    public interface ICA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/JoinClient", ReplyAction="http://tempuri.org/ICA/JoinClientResponse")]
        Client.CAService.JoinClientResponse JoinClient(Client.CAService.JoinClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/JoinServer", ReplyAction="http://tempuri.org/ICA/JoinServerResponse")]
        Client.CAService.JoinServerResponse JoinServer(Client.CAService.JoinServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/RegistrateClient", ReplyAction="http://tempuri.org/ICA/RegistrateClientResponse")]
        Client.CAService.RegistrateClientResponse RegistrateClient(Client.CAService.RegistrateClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/RegistrateServer", ReplyAction="http://tempuri.org/ICA/RegistrateServerResponse")]
        Client.CAService.RegistrateServerResponse RegistrateServer(Client.CAService.RegistrateServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/AliveClient", ReplyAction="http://tempuri.org/ICA/AliveClientResponse")]
        Client.CAService.AliveClientResponse AliveClient(Client.CAService.AliveClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/AliveServer", ReplyAction="http://tempuri.org/ICA/AliveServerResponse")]
        Client.CAService.AliveServerResponse AliveServer(Client.CAService.AliveServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICA/IsAlive", ReplyAction="http://tempuri.org/ICA/IsAliveResponse")]
        Client.CAService.IsAliveResponse IsAlive(Client.CAService.IsAliveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JoinClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JoinClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string data;
        
        public JoinClientRequest() {
        }
        
        public JoinClientRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JoinClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JoinClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string JoinClientResult;
        
        public JoinClientResponse() {
        }
        
        public JoinClientResponse(string JoinClientResult) {
            this.JoinClientResult = JoinClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JoinServer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JoinServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string data;
        
        public JoinServerRequest() {
        }
        
        public JoinServerRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="JoinServerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class JoinServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string JoinServerResult;
        
        public JoinServerResponse() {
        }
        
        public JoinServerResponse(string JoinServerResult) {
            this.JoinServerResult = JoinServerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrateClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string data;
        
        public RegistrateClientRequest() {
        }
        
        public RegistrateClientRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrateClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrateClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RegistrateClientResult;
        
        public RegistrateClientResponse() {
        }
        
        public RegistrateClientResponse(string RegistrateClientResult) {
            this.RegistrateClientResult = RegistrateClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrateServer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrateServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string data;
        
        public RegistrateServerRequest() {
        }
        
        public RegistrateServerRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrateServerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrateServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RegistrateServerResult;
        
        public RegistrateServerResponse() {
        }
        
        public RegistrateServerResponse(string RegistrateServerResult) {
            this.RegistrateServerResult = RegistrateServerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AliveClient", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AliveClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string data;
        
        public AliveClientRequest() {
        }
        
        public AliveClientRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AliveClientResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AliveClientResponse {
        
        public AliveClientResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AliveServer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AliveServerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string data;
        
        public AliveServerRequest() {
        }
        
        public AliveServerRequest(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AliveServerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AliveServerResponse {
        
        public AliveServerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAlive", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAliveRequest {
        
        public IsAliveRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAliveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsAliveResult;
        
        public IsAliveResponse() {
        }
        
        public IsAliveResponse(bool IsAliveResult) {
            this.IsAliveResult = IsAliveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICAChannel : Client.CAService.ICA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAClient : System.ServiceModel.ClientBase<Client.CAService.ICA>, Client.CAService.ICA {
        
        public CAClient() {
        }
        
        public CAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.CAService.JoinClientResponse JoinClient(Client.CAService.JoinClientRequest request) {
            return base.Channel.JoinClient(request);
        }
        
        public Client.CAService.JoinServerResponse JoinServer(Client.CAService.JoinServerRequest request) {
            return base.Channel.JoinServer(request);
        }
        
        public Client.CAService.RegistrateClientResponse RegistrateClient(Client.CAService.RegistrateClientRequest request) {
            return base.Channel.RegistrateClient(request);
        }
        
        public Client.CAService.RegistrateServerResponse RegistrateServer(Client.CAService.RegistrateServerRequest request) {
            return base.Channel.RegistrateServer(request);
        }
        
        public Client.CAService.AliveClientResponse AliveClient(Client.CAService.AliveClientRequest request) {
            return base.Channel.AliveClient(request);
        }
        
        public Client.CAService.AliveServerResponse AliveServer(Client.CAService.AliveServerRequest request) {
            return base.Channel.AliveServer(request);
        }
        
        public Client.CAService.IsAliveResponse IsAlive(Client.CAService.IsAliveRequest request) {
            return base.Channel.IsAlive(request);
        }
    }
}
